Repository WildCodeSchool-2023-09/JS-RemoteFR-SACOD-P2-Red-Force, pull requests merged in 2023-11, with the labels that each got.

#19 🐛 FIX: Pages Bugs
  frontend/src/App.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Quiz.jsx
  frontend/src/scss/navbar.scss
  frontend/src/scss/root.scss
Labels: REVIEWED

#23 🚀 RELEASE: ScoreBoard
  frontend/src/App.jsx
  frontend/src/components/ScoreCard.jsx
  frontend/src/components/buttons/Question.jsx
  frontend/src/data/navdata.json
  frontend/src/main.jsx
  frontend/src/pages/Quiz.jsx
  frontend/src/pages/ScoreBoard.jsx
  frontend/src/scss/components/scorecard.scss
  frontend/src/scss/root.scss
  frontend/src/scss/scoreboard.scss
Labels: REVIEWED, CORRECTIONS DONE

#24 S02 us02 score logic
  frontend/src/components/Life.jsx
  frontend/src/components/QuizCard.jsx
  frontend/src/pages/Quiz.jsx
  frontend/yarn.lock
Labels: CONFLICTS RESOLVED

#26 category page done
  frontend/src/components/buttons/Category.jsx
  frontend/src/data/category.json
  frontend/src/main.jsx
  frontend/src/pages/CategoryPage.jsx
  frontend/src/scss/categorypage.scss
Labels: CONFLICTS RESOLVED

#28 🐛 FIX: Fixing Merge
  frontend/src/components/ScoreCard.jsx
  frontend/src/components/buttons/ResponseBtn.jsx
  frontend/src/data/navdata.json
  frontend/src/main.jsx
  frontend/src/pages/CategoryPage.jsx
  frontend/src/pages/Quiz.jsx
  frontend/src/pages/ScoreBoard.jsx
  frontend/src/scss/categorypage.scss
  frontend/src/scss/components/buttons.scss
  frontend/src/scss/components/question.scss
  frontend/src/scss/home.scss
  frontend/src/scss/root.scss
Labels: REVIEWED

#30 S03 us01 send url of api
  frontend/index.html
  frontend/public/assets/.htaccess
  frontend/src/App.jsx
  frontend/src/components/DifficultyCard.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/QuizCard.jsx
  frontend/src/components/buttons/Buttons.jsx
  frontend/src/components/buttons/Category.jsx
  frontend/src/data/category.json
  frontend/src/data/homepage-titles.json
  frontend/src/main.jsx
  frontend/src/pages/CategoryPage.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Quiz.jsx
  frontend/src/pages/ScoreBoard.jsx
  frontend/src/scss/components/category.scss
  frontend/src/scss/difficultycard.scss
  frontend/src/scss/root.scss
Labels: REVIEWED

#31 Update README.md
  README.md
Labels: REVIEWED

#35 Fixing bugs
  frontend/index.html
  frontend/public/assets/.htaccess
  frontend/public/assets/share-cover.png
  frontend/src/data/homepage-titles.json
Labels: REVIEWED

#34 Update README.md
  README.md
Labels: REVIEWED

#36 🐛 FIX: HTACCESS
  frontend/public/.htaccess
  frontend/src/main.jsx
  frontend/src/scss/root.scss
Labels: REVIEWED

#37 🐛 FIX: HTACCESS and LINKS
  frontend/index.html
  frontend/public/.htaccess
Labels: REVIEWED
